name: Maestro
version: "0.1.3"
slug: maestro
description: Home Assistant lights orchestrator
startup: application
boot: auto
build_from:
  amd64: ghcr.io/home-assistant/amd64-addon-base:14
options:
  baseurl: http://homeassistant.local:8123/
  token: ''
  simulate: false
  no_notify: false
  program: default
schema:
  baseurl: str?
  token: str?
  simulate: bool
  no_notify: bool
  program: str?
image: local/maestro
arch:
  - amd64
  - armhf
  - aarch64
  - i386