name: Build Home Assistant Add-on

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-addon:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Get version from config
        id: get_version
        run: |
          VERSION=$(jq -r '.version' maestro/config.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push add-on image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: maestro/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-base:3.15
          tags: |
            ghcr.io/${{ github.repository_owner }}/aarch64-maestro:latest
            ghcr.io/${{ github.repository_owner }}/aarch64-maestro:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/aarch64-maestro:${{ steps.get_version.outputs.version }}
