name: Build Home Assistant Add-on

on:
  push:
    branches: [ main ]

jobs:
  build-addon:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"

      - name: Build Maestro server
        run: swift build --configuration release

      - name: Copy Maestro binary into add-on
        run: |
          mkdir -p maestro/rootfs/bin
          cp .build/release/maestro maestro/rootfs/bin/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push add-on image
        uses: docker/build-push-action@v6
        with:
          context: ./maestro
          file:   ./maestro/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/maestro:latest