name: Debug Image Publishing

on:
  workflow_dispatch:  # This allows manual triggering

permissions:
  contents: read
  packages: write

jobs:
  debug-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"

      - name: Build Maestro server
        run: swift build --configuration release

      - name: Copy Maestro binary into add-on
        run: |
          mkdir -p maestro/rootfs/bin
          cp .build/release/maestro maestro/rootfs/bin/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug image build and push
        run: |
          echo "Building image..."
          docker buildx build \
            --platform linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/aarch64-maestro:debug \
            -f maestro/Dockerfile \
            ./maestro \
            --push

          echo "Verifying image..."
          docker pull ghcr.io/${{ github.repository_owner }}/aarch64-maestro:debug

          echo "Checking image details..."
          docker inspect ghcr.io/${{ github.repository_owner }}/aarch64-maestro:debug

          echo "Listing available tags..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://ghcr.io/v2/${{ github.repository_owner }}/aarch64-maestro/tags/list | jq . 