name: Publish Docker image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/maestro
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./maestro
          file: ./maestro/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base/amd64:13.2.0
            BUILD_ARCH=amd64
            BUILD_VERSION=${{ github.ref_name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/maestro:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title=Maestro
            org.opencontainers.image.description=Maestro add-on for Home Assistant
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
